name: 'My Python Action'
description: 'Execute Python code'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.8'
  message:
    description: 'Optional message to print'
    required: false
    default: 'Hello, world!'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      shell: bash
      run: python my_script.py --message "${{ inputs.message }}"
